### ISSUE TITLE
Delete not removing duplicates

### ISSUE THREAD

**Issue by horphi0815** [daman20/Deduper#4]
Depuper is starting now. :-) 

After Hashing the result shows the duplicates. 
By selecting the checkbox and click ok, the duplicates not get physically removed and there is no chance to select the original, which should stay...or i didn´t understand the mechnism.

Now Calculating : /scan/20150816_182646.jpg
Now Calculating : /scan/1.jpg
Now Calculating : /scan/2.jpg
<_io.TextIOWrapper name='/appdata/hashes.json' mode='a+' encoding='UTF-8'>
created deletedupe window
EVENT IS: Done
VALUES IS: {0: True}
Numbers to be deleted is [0]
Traceback (most recent call last):
File "/main.py", line 14, in <module>
deletedupes.main()
File "/deletedupes.py", line 40, in main
filetobedeleted = list(result)[i]
IndexError: list index out of range
[app] starting Deduper...
Now Calculating : /scan/20150816_182646.jpg
Now Calculating : /scan/1.jpg
Now Calculating : /scan/2.jpg
<_io.TextIOWrapper name='/appdata/hashes.json' mode='a+' encoding='UTF-8'>
created deletedupe window
EVENT IS: Done
VALUES IS: {0: False}
Numbers to be deleted is []
Dupes to be deleted is []
Cleaning Up
[app] starting Deduper...
Now Calculating : /scan/20150816_182646.jpg
Now Calculating : /scan/1.jpg
Now Calculating : /scan/2.jpg
<_io.TextIOWrapper name='/appdata/hashes.json' mode='a+' encoding='UTF-8'>
created deletedupe window
EVENT IS: Done
VALUES IS: {0: True}
Numbers to be deleted is [0]
Traceback (most recent call last):
File "/main.py", line 14, in <module>
deletedupes.main()
File "/deletedupes.py", line 40, in main
filetobedeleted = list(result)[i]
IndexError: list index out of range
[app] starting Deduper...
Now Calculating : /scan/20150816_182646.jpg
Now Calculating : /scan/1.jpg
Now Calculating : /scan/2.jpg
<_io.TextIOWrapper name='/appdata/hashes.json' mode='a+' encoding='UTF-8'>
created deletedupe window
EVENT IS: Done
VALUES IS: {0: True}
Numbers to be deleted is [0]
Traceback (most recent call last):
File "/main.py", line 14, in <module>
deletedupes.main()
File "/deletedupes.py", line 40, in main
filetobedeleted = list(result)[i]
IndexError: list index out of range
[app] starting Deduper...

![grafik](https://user-images.githubusercontent.com/39962016/123746754-5b271b80-d8b2-11eb-9efb-0b790b1f6ac7.png)

**Comment by horphi0815** [comment]
Some news regarding this?

BR

Phil
